# Generated by Django 4.2.2 on 2023-06-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meaty_app', '0002_alter_user_domisili_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usia',
            field=models.IntegerField(null=True),
        ),
    ]
